### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by michaliskok** [rems-project/rmem#2]
Hello,

I am encountering a build error while trying to install `rmem` with Ocaml 4.07. (I also tried v4.06, but to no avail.)

The build fails at the following command:

`../lem/lem -only_changed_output -wl_unused_vars ign -wl_pat_comp ign -wl_pat_exh ign -wl_comp_message ign -wl_rename ign -wl_pat_red ign -outdir build_concurrency_model/ -ocaml build_sail_interp/interp_lib.lem build_sail_interp/interp_interface.lem build_sail_interp/interp_utilities.lem build_sail_interp/interp.lem build_sail_interp/sail_impl_base.lem build_sail_interp/interp_inter_imp.lem build_sail_interp/interp_ast.lem build_sail_interp/instruction_extractor.lem build_sail_shallow_embedding/deep_shallow_convert.lem build_sail_shallow_embedding/sail_values.lem build_sail_shallow_embedding/prompt.lem build_sail2_shallow_embedding/sail2_instr_kinds.lem build_sail2_shallow_embedding/sail2_values.lem build_sail2_shallow_embedding/sail2_operators.lem build_sail2_shallow_embedding/sail2_operators_mwords.lem build_sail2_shallow_embedding/sail2_prompt_monad.lem build_sail2_shallow_embedding/sail2_prompt.lem build_sail2_shallow_embedding/sail2_string.lem src_concurrency_model/utils.lem src_concurrency_model/freshIds.lem build_isa_models/power/power_extras_embed.lem build_isa_models/power/power_embed_types.lem build_isa_models/power/power_embed.lem src_concurrency_model/isaInfoPPCGen.lem build_isa_models/power/power_extras.lem build_isa_models/aarch64/armV8_extras_embed.lem build_isa_models/aarch64/armV8_embed_types.lem build_isa_models/aarch64/armV8_embed.lem src_concurrency_model/isaInfoAArch64.lem build_isa_models/aarch64/armV8_extras.lem src_concurrency_model/isa_stubs/mips/mips_embed_types.lem src_concurrency_model/isa_stubs/mips/mips_embed.lem src_concurrency_model/isa_stubs/mips/isaInfoMIPS.lem src_concurrency_model/isa_stubs/mips/mips_extras.lem build_isa_models/riscv/riscv_extras.lem build_isa_models/riscv/riscv_types.lem build_isa_models/riscv/riscv.lem src_concurrency_model/isaInfoRISCV.lem build_isa_models/x86/x86_extras_embed.lem build_isa_models/x86/x86_embed_types.lem build_isa_models/x86/x86_embed.lem src_concurrency_model/isaInfoX86.lem build_isa_models/x86/x86_extras.lem src_concurrency_model/instructionSemantics.lem src_concurrency_model/events.lem src_concurrency_model/fragments.lem src_concurrency_model/basicTypes.lem src_concurrency_model/regUtils.lem src_concurrency_model/uiTypes.lem src_concurrency_model/params.lem src_concurrency_model/dwarfTypes.lem src_concurrency_model/candidateExecution.lem src_concurrency_model/machineDefTypes.lem src_concurrency_model/machineDefUI.lem src_concurrency_model/machineDefPLDI11StorageSubsystem.lem src_concurrency_model/machineDefFlowingStorageSubsystem.lem src_concurrency_model/machineDefFlatStorageSubsystem.lem src_concurrency_model/machineDefPOPStorageSubsystem.lem src_concurrency_model/machineDefNOPStorageSubsystem.lem src_concurrency_model/machineDefTSOStorageSubsystem.lem src_concurrency_model/machineDefInstructionPredicates.lem src_concurrency_model/machineDefThreadSubsystemUtils.lem src_concurrency_model/machineDefThreadSubsystem.lem src_concurrency_model/machineDefSystem.lem src_concurrency_model/machineDefTransitionUtils.lem src_concurrency_model/promisingViews.lem src_concurrency_model/promisingTransitions.lem src_concurrency_model/promisingUtils.lem src_concurrency_model/promisingThread.lem src_concurrency_model/promisingStorage.lem src_concurrency_model/promising.lem src_concurrency_model/promisingDwarf.lem src_concurrency_model/promisingUI.lem build_isa_models/power/power_toFromInterp.lem build_isa_models/aarch64/armV8_toFromInterp.lem src_concurrency_model/isa_stubs/mips/mips_toFromInterp.lem src_concurrency_model/isa_stubs/riscv/riscv_toFromInterp.lem build_isa_models/x86/x86_toFromInterp.lem
File "build_isa_models/riscv/riscv_extras.lem", line 11, character 35 to line 11, character 56
  Type error: type mismatch: application expression
    unit -> _
  and
    Sail2_instr_kinds.barrier_kind`

Please find the complete output log [here](https://github.com/rems-project/rmem/files/3435148/output.log).

Thank you,
Michalis

**Comment by fshaked** [comment]
Temporarily you need to use the union_barrier branch instead of sail2. From the rmem folder do this:
$ cd ../sail2
$ git checkout union_barrier
$ make clean
$ cd ../sail-riscv
$ make clean
$ cd ../rmem
$ make MODE=opt

**Comment by michaliskok** [comment]
Thanks, that did the trick! Feel free to close the issue.

Just out of curiosity, does this affect the functionality/performance of the tool in any way?

**Comment by fshaked** [comment]
No. We added to sail support for ARM barrier domains (i.e. sy/ish/osh/nsh) but did not actually model them in the currency model. We just assume the hardware configuration is such that sy and ish behave in the same way.

**Comment by fshaked** [comment]
RMEM builds again with the sail2 branch.

**Comment by michaliskok** [comment]
Hello,

I encounter a build failure again when building the most recent version of the tool. The compiler complains about `L.141` in `src_top/text/screen.ml` (see below for the exact error).

I checked out some previous commits and downgraded my zed version, but I still get an error. Any tips on how to fix this?

Thanks,
Michalis

```
File src_top/text/screen.ml, line 141, characters 10-48:
  inherit [Zed_utf8.t] LTerm_read_line.term term
Error: The method eval has type Zed_string.t but is expected to have type
         Zed_utf8.t
       Type Zed_string.t is not compatible with type Zed_utf8.t = string 
Command exited with code 2.
```

**Comment by cp526** [comment]
What's your OCaml version? I'm running 4.07.0, with packages zed in version 1.6 and lambda-term in version 1.13, where it builds as expected.

**Comment by michaliskok** [comment]
Ah, it seems I did not downgrade enough (used 2.0.0 instead). The above combination worked, thank you. (For the record, I am using OCaml 4.07 since, IIRC, 4.09 would not work.)
