### ISSUE TITLE
coq/isabelle formalization of the inter-instruction semantics

### ISSUE THREAD

**Issue by aa755** [rems-project/rmem#22]
If I understand correctly, this repo implements (among other things) Section 6.2-6.5 of the paper [Simplifying ARM Concurrency: Multicopy-atomic Axiomatic and Operational Models for ARMv8](http://doi.acm.org/10.1145/3158107) in Ocaml.
Is there a logical formalization of the inter-instruction semantics described in that part of the paper? If not, is there a way to extract it somehow from this repo?

**Comment by PeterSewell** [comment]
The executable version of that and other operational models are in Lem, e.g.:
- the common Thread Subsystem (which is used for several models):  https://github.com/rems-project/rmem/blob/bcb20633b6e292d3ea96029f8f2d93e537eb81b2/src_concurrency_model/machineDefThreadSubsystem.lem
- the Flat storage subsystem model: https://github.com/rems-project/rmem/blob/master/src_concurrency_model/machineDefFlatStorageSubsystem.lem

There is not at present a Coq or Isabelle version of these.  Lem has some support for translating .lem definitions into Isabelle and Coq, and we've experimented with that for these models in the past, but they're not currently set up for it, and really (especially for Coq) they would have to be rephrased.   We have in mind to do that for Coq in future, but not right now.  What would you want to do with it?  (Perhaps better by email)
