### ISSUE TITLE
forwarding reads to other reads

### ISSUE THREAD

**Issue by aa755** [rems-project/rmem#23]
In section 6.4 of [Simplifying ARM Concurrency: Multicopy-atomic Axiomatic and Operational Models for ARMv8](http://doi.acm.org/10.1145/3158107), the inter-instruction semantics talks about forwarding writes to reads, e.g.:
![image](https://github.com/rems-project/rmem/assets/499314/2567368b-c33f-43a4-9f48-3d2fb758eeb4)
But it doesnt seem to talk about forwarding reads to other reads of the same location. Does ARM do that? if so, how does SAIL+RMEM capture it? More concretely, consider the following example:
`LD 300 x0; LD 300; x1`. Must the CPU issue 2 read requests to the memory? If not, how does SAIL+RMEM model the "forwarding" of the value read in one instruction to the other?

**Comment by fshaked** [comment]
Hi Abhishek, as far as we know, the architecture does not allow "read forwarding" to be visible (in ways that are not already accounted for by the model). The model will satisfy each read individually, either by forwarding or from storage (it never copies the value from one read to another). Nevertheless, the uarch is free to issue a single request for multiple reads if it can be sure this is not visible (does not produce behaviour that the model forbids). For example, I think in most reasonable uarchs it will be safe to issue a single request when two loads are identical, and there's no other instruction between them.

Shaked

**Comment by aa755** [comment]
Thanks. So it seems SAIL+RMEM is really a combined model of CPUs+DRAM. In a model of just the CPU (excludes DRAM), e.g. in a LTS (labeled transition system) style, the missing read event (e.g. in the case you described:  two loads are identical, and there's no other instruction between them) would be visible. 
Do you think it is possible/easy to write an isolated model of just the CPU, e.g. by explicitly modeling the "read forwarding" in RMEM, possibly with lots of nondeterminism? Would other changes be needed to make SAIL+RMEM be a model of just the CPU (without DRAM)?

**Comment by PeterSewell** [comment]
Sail+RMEM are intended as a model of the architectural programmer-visible
behaviour.  A high-performance hardware implementation will typically have
a very fancy interconnect and cache hierarchy - I don't know what you would
want to include within "just the CPU".  Or why, unless you're doing
hardware verification, which I guess you're not.  What are you aiming for?

**Comment by aa755** [comment]
> Or why, unless you're doing hardware verification, which I guess you're not

A VMM is in a sense an implementation of hardware.  To modularize the VMM proof, it may help to break down the idealized model of an ARM VMM (an ARM baremetal model) into smaller independent pieces that communicate to other pieces via events, in the sense of LTS composition. Until the discussion in this issue, we were thinking that SAIL+RMEM is an independent model of a CPU thread along with the data caches, and we could lts-compose it with a simple DRAM model that just records the latest write to every location (and further compose that with lts models of devices like ethernet controller, PL011).

**Comment by gmalecha** [comment]
@PeterSewell We are actively working on something to share more details with you. We've been focused on a core-local semantics to constrain our reasoning and to account for features such as MMIO requests even when page tables are potentially mis-configured (as a guest might do either by accident or maliciously).
