### ISSUE TITLE
Simple example for AArch64 does not terminate

### ISSUE THREAD

**Issue by db7** [rems-project/rmem#4]
I'm trying to run this simple example for AArch64:

```
AArch64 loop
{
    x=0;
    0:X0=x;
}

        P0;
L01:    LDR W1,[X0];
        CBNZ W1,L01;
        MOV W1,#1;
        STR W1,[X0];

exists (x=0)
```

Since x is initially 0, the conditional branch should be skipped and 1 should be stored in x, AFAICT.

Running rmem/flat in non-interactive mode never terminates. Similarly, the exhaustive search in the interactive mode does not terminate. If I simply auto-step (a) in interactive mode, the execution terminates as expected.

This is how I am calling the rmem tool in non-interactive mode:
```
flat -interactive false -eager true example.litmus
```

Am I missing some obvious configuration or step? Do you have any suggestion how to discover what is going on? Thank you.

Note: rmem built with OCaml 4.06.1 at commit 3822f35.

**Comment by cp526** [comment]
Hi!

This is expected behaviour due to how the Flat model works: loops, also
statically bounded ones, cause the exhaustive exploration to infinitely loop. (More details below.)

Adding the option ` -loop_limit n` (for some number n, say 2) gives the expected terminating behaviour.

(Also note, that `./flatOpt` turns on some optimisations for faster
exhaustive exploration, or `./promisingOpt`, for the Promising model that runs faster.)



More detail: in the Flat model, new instructions can be fetched before old instructions are finished/retired, in order to allow all the relaxed behaviours. This means, in this example, the LDR instruction at label L01 can be fetched as a successor of CBNZ before the CBNZ branch has been executed, and so before it is known whether the branch is taken or not. The model can then infinitely often extend the instruction tree with `LDR W1,[X0]; CBNZ W1,L01; LDR W1,[X0]; CBNZ W1,L01; ..`

**Comment by db7** [comment]
Excellent! Thank you for the detailed explanation, it makes sense.

**Comment by fshaked** [comment]
Note that in the test above the loop limit only affects executions where the branch prediction is "wrong" and therefore it does not affect the observable final states rmem reports at the end. In tests where the loop limit affects some "correct" branch, the report at the end of the run will indicate that there were unhandled exceptions. Try changing the CBNZ to CBZ to see how rmem reports it.

**Comment by db7** [comment]
@fshaked, thanks for the reply. Did I understand correctly that we should see exceptions if the loop limit makes the test miss important behaviors? That would be nice.

Regarding your suggestion, by changing CBNZ to CBZ, I get rather "deadlock states", but no exceptions:
```
% flatOpt -interactive false -eager true -loop_limit 2 example.litmus 
Test deadlock Allowed
Memory-writes=
States 0
Deadlock states 12  via "0;0"
Unhandled exceptions 0

No (allowed not found)
Condition exists (x=0)
Hash=6b78dae9bb71940e79855ed290e4b9a2
Observation deadlock Never 0 0 with deadlocks
Runtime: 0.421554 sec
```

Have I misconfigured something?

**Comment by fshaked** [comment]
I get this:
```
$ ./flatOpt test.litmus -interactive false -eager true -loop_limit 2
Test loop Allowed
Memory-writes=
States 0
Deadlock states 5  via "0;0"
Unhandled exceptions 3
1     :>thread 0 instruction 0:5: reached loop limit via "0;0"
2     :>thread 0 instruction 0:7: reached loop limit via "0;2;0"
2     :>thread 0 instruction 0:9: reached loop limit via "1;2;4;0;1"

No (allowed not found)
Condition exists (x=0)
Hash=6b78dae9bb71940e79855ed290e4b9a2
Observation loop Never 0 0 with deadlocks with unhandled exceptions
Runtime: 0.456092 sec
```

**Comment by db7** [comment]
I copied again the code above and changed CBNZ to CBZ -- just to be sure. Indeed, I am not getting any exceptions. So, I guess there must be something wrong with my build. I am running rmem of commit 3822f35 (from last week) with OCaml 4.06.1.

Is there a commit that is considered "safe"?

Or any suggestion how to debug this?

If the output of the tool is incorrect in my build, then this may also influence issue #6.

**Comment by fshaked** [comment]
I'm using 40babcd (most recent), try pulling and rebuilding rmem. I do not immediately see why we should get different results, but this seems like a reasonable first step.

Unfortunately, we do not have a "safe" version. We run regression tests every night and try to fix bugs as soon as we find them.

**Comment by db7** [comment]
Nice, updating the tool fixed the issue and now my output is similar to yours! Thank you.

What is the approach to deal with such exceptions? Should I increase the loop limit until I don't see them anymore?

**Comment by fshaked** [comment]
There is no simple solution to that. You need to know the code you're testing and do whatever is appropriate for it. For example, if you know all the loops in the code have some upper bound, use that and you should not get this exception. If you have a wait loop in the code then there is no such bound but, usually executing the body of a wait loop multiple times does not affect the observable final states, so you should be able to convince yourself that some limit, even though it generates the exceptions, is safe for your wait loop.

**Comment by db7** [comment]
Ok, sounds reasonable. Thanks!
