### ISSUE TITLE
Feasibility of exhaustive tests

### ISSUE THREAD

**Issue by db7** [rems-project/rmem#7]
I'm trying to understand whether or when it is feasible to perform exhaustive tests with rmem. So far my experience was that showing something is wrong is pretty quick (which is awesome), but showing that something is correct often does not terminate.

I'm trying simple pieces like `lock(); var++; unlock();`. One actual litmus test I am using is below. 

For example,
- `flatOpt` with loop-limit terminates 10000 random traces of this code in 25 minutes, which is fine. But I guess that I can make no claim about the coverage of such test. The actual number of executions can only be counted by exhaustively running the model. Is that right?
- exhaustive testing this code with `flatOpt` does not terminate after running for 2 days. Btw, the tool seem to use only a single core of the host. Is that by design or am I missing some configuration?
- I had no luck with `promisingOpt`. It consumes much more memory than `flatOpt` and does not terminate even for a few random traces.
- I also tried `-eager_fetch_unmodified`, which then quickly terminates but does not find all final states. I guess I don't understand what this option does.

So, I am wondering how to use rmem to verify code that we believe to be correct. Are people doing this? Do you have any suggestion how to tackle an exhaustive verification of the following example? 

```
AArch64 spinlock
(* 
 * Critical section with load-/store-exclusive spinlock.
 * https://github.com/ARM-software/arm-trusted-firmware/blob/master/lib/locks/exclusive/aarch64/spinlock.S
 *)
{
    uint32_t lock=0;
    var=0;

    0:X0=lock ;  1:X0=lock ;
    0:X3=var  ;  1:X3=var  ;
}

        P0               |          P1              ;

(* lock ********************************************)
        MOV W2,#1        |          MOV W2,#1       ;
L01:    LDAXR W1,[X0]    |  L11:    LDAXR W1,[X0]   ;
        CBNZ W1,L01      |          CBNZ W1,L11     ;
        STXR W1,W2,[X0]  |          STXR W1,W2,[X0] ;
        CBNZ W1,L01      |          CBNZ W1,L11     ;

(* critical section ********************************)
        LDR W6,[X3]      |          LDR W6,[X3]     ;
        ADD W6,W6,#1     |          ADD W6,W6,#1    ;
        STR W6,[X3]      |          STR W6,[X3]     ;
                          
(* unlock ******************************************) 
        STLR WZR,[X0]    |          STLR WZR,[X0]   ;

exists (lock!=0 \/ (0:X6 = 1 /\ 1:X6 = 1))
```

**Comment by cp526** [comment]
We've done a bit of exhaustive checking of programs in the past: some spinlock examples and other concurrent data structures. 

For the particular example, did you use a loop limit when running? (As the test has loops, without the loop limit the exhaustive execution will not terminate.) 

In general, exhaustive checking should work best with the Promising model, if the test does not need features not currently implemented for Promising: mixed-size memory accesses or self-modifying code. I just made a change which makes Promising respect the loop limit, and another which I hope fixes/improves the memory consumption issue. Thanks for reporting the issue. 

For your example, I'm now getting the output below:
```
christopher@christophers-laptop:~/Sources/rmem$ ~/Sources/rmem/promisingOpt -interactive false ../../asd.litmus -loop_limit 3
Test spinlock Allowed
Memory-writes=
States 2
216   :>0:X6=1; 1:X6=2; lock=0;  via "1;0;0;1;0;0;0;2;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
216   :>0:X6=2; 1:X6=1; lock=0;  via "3;3;0;1;0;0;0;8;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
Deadlock states 973  via "1;1;0;0"
Unhandled exceptions 10
40    :>thread 0 instruction 0:6: reached loop limit via "3;3;0;0;0;0;0;0;0;0;0"
56    :>thread 0 instruction 0:10: reached loop limit via "3;3;0;0;4;0;0;0;0;0;0;0;0;0;0"
271   :>thread 0 instruction 0:12: reached loop limit via "0;0;0;0;0;0;0;0;0;0;0;0;0;0"
144   :>thread 0 instruction 0:14: reached loop limit via "3;3;0;0;24;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
72    :>thread 0 instruction 0:16: reached loop limit via "3;3;0;0;40;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
30    :>thread 1 instruction 1:6: reached loop limit via "1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
42    :>thread 1 instruction 1:10: reached loop limit via "1;0;0;0;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
144   :>thread 1 instruction 1:12: reached loop limit via "1;0;0;0;2;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
108   :>thread 1 instruction 1:14: reached loop limit via "1;0;0;0;6;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"
54    :>thread 1 instruction 1:16: reached loop limit via "1;0;0;0;10;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0"

No (allowed not found)
Condition exists (not (lock=0) \/ 0:X6=1 /\ 1:X6=1)
Hash=38aa9d1fdad5a92505f642b7639393de
Observation spinlock Never 0 2 with deadlocks with unhandled exceptions
Runtime: 18.694338 sec
```


Thanks also for reporting the `-eager_fetch_unmodified` issue. This command line argument is meant only in combination with the relaxed-instruction-fetch model (and so not needed here). We will look into why this is returning fewer states.

**Comment by db7** [comment]
@cp526, thank you for fixing the loop-limit and memory issue of promising! Now I get promisingOpt to terminate with my examples. 

However, I am still unsure of how to proceed with exhaustive tests: In the spinlock example above, I get results in a few seconds, but there are several exceptions. The only way to be sure that the code is correct wrt the model is to increase the loop limit until no exceptions are left. In this example, I tried several loop limits (up to 24) and after several hours it still terminates with exceptions (or goes out of memory).

In issue #4, @fshaked suggested that the only way to test code with unbounded loops (any spinlock, ticketlock, rwlock, semaphore, cmpxchg, ...) is "know the code you're testing":

> If you have a wait loop in the code then there is no such bound but, usually executing the body of a wait loop multiple times does not affect the observable final states, so you should be able to convince yourself that some limit, even though it generates the exceptions, is safe for your wait loop.

Could you help me to convince myself that the wait loop in the example spinlock won't affect observable final states? I definitely see that the instructions inside the wait loop (LDAXR and CBNZ) do not change any state, but after the wait loop finishes, the program increments var! So I must be missing something.

**Comment by cp526** [comment]
Good to hear the model is running ok on your example now. 

Unfortunately, there is no general solution for the exhaustive enumeration question for unbounded loops: unless loops are statically bounded in the program or by a user-supplied loop limit the exhaustive enumeration will be infinite.

In your particular example, if I understand the program correctly, it looks like the possible concurrent executions one can see do not depend on how often the loops are executed as long as they are executed at least once: whether it's one iteration or hundreds does not seem to affect the possible states. 

I'm not sure I understand why 'var' is problematic: 'var' is updated only after leaving the loop body, and so the number of loop iterations should not matter.
